ALTER TABLE chairs ADD COLUMN total_distance INTEGER NOT NULL DEFAULT 0 COMMENT '合計移動距離';
ALTER TABLE chairs ADD COLUMN total_distance_updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '合計移動距離の更新日時';
